name: Testing the library

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
      - name: run lint
        run: cargo fmt --all --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: execute lib tests
        uses: actions-rs/cargo@v1
        with:
          command: test
  check-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: taiki-e/install-action@cargo-hack
      - name: execute lib tests
        run: cargo hack check --feature-powerset --tests
